### ISSUE TITLE
Implementing custom providers 

### ISSUE THREAD

**Issue by rberghegger** [SAP/gigya-android-sdk#10]
Hello everyone 👋 
is it possible to implement custom providers for social sign in?
In the current SDK there is a class `Provider` that's extended by some pre-build providers (Facebook, Google etc.).
I wonder if there is a public API that allows us to add our own provider implementation to the Gigya SDK?
For example if we want to add a provider that's currently not supported by the Gigya SDK or because we don't want to add the Facebook SDK to our application to support login with Facebook.

With the iOS SDK it is possible to provide a custom `FacebookWrapper` implementation.

**Comment by tal-mi** [comment]
Hi,
Using the SDK you are only able to apply social login flows to a Gigya supported provider in order to correctly create your session.
If you still want to implement the entire supported provider's logic your self, you will be required to use the [notifySocialLogin](https://developers.gigya.com/display/GD/accounts.notifySocialLogin+REST) endpoint in order to create your session.

If you would like to create your own custom provider I suggest you look into the [OIDC](https://developers.gigya.com/display/GD/OpenID+Connect) pattern.
