### ISSUE TITLE
Migrate to AndroidX

### ISSUE THREAD

**Issue by andersu** [SAP/gigya-android-sdk#2]
We are trying to disable jetifier in our app to get a faster build.
Gigya is our only dependency that still uses the Android support library.

Please replace the support library dependencies with AndroidX:
https://developer.android.com/jetpack/androidx/migrate

**Comment by tal-mi** [comment]
Hi,

Upgrading our SDK to use AndroidX is a priority and we will soon address this.

Thanks,
Tal

**Comment by peter-budo** [comment]
@tal-mi you guys should be working on it faster

- Plugin version 3.5.x that you strongly suggest to use been released in August 2019 
- Plugin version 3.6.x that should not be used been released in February 2020
- Now we have version 4.0.x released in April 2020

Almost 6 months later and there is nothing to show for on your end. 
Given this is paid product this is putting whole your company in bad image. But I guess I should be thankful that after 2+ years somebody up there woke up and made this libraries distributed, build tolls fetched dependencies, instead of manual updates that we had till this day

**Comment by tal-mi** [comment]
Hi Peter,
I appreciate you comment here.
As I mentioned, AndroidX upgrade (including supporting the latest plugin version) is a high priority.
Due to the nature of this change we cannot rush it as it can affect clients differently.
I will continue to update in this thread.

You are also able to open a support case using:
https://developers.gigya.com/display/GD/Opening+A+Support+Incident

Thanks,
Tal

**Comment by tal-mi** [comment]
Just to update:
Next SDK core update will be the last before migrating to AndroidX.
Will continue to update here until resolved.

Thanks,
Tal

**Comment by tal-mi** [comment]
Resolved with 5.0.0 & extension 2.0.0 releases.
